### ISSUE TITLE
trying to run with nivida gpu on pc

### ISSUE THREAD

**Issue by rnunziata** [ducandu/RL-Implementation-IMPALA#2]
trying to run with nivida gpu  gtx1060 on pc  ... post seem to imply that tensorflow server_model  needs to be compiled from source setting the config to cuda for gpu support. However I have not been able to get this to compile with gpu.  Has anyone tried to run the learner with gpu on ubuntu? What about nivida-docker? CPU works fine.

**Comment by sven1977** [comment]
Hi,
I'm very sorry, but I will not have the time to further improve this repo right now.
However, please check out our newest RL-library (still in an early dev/pre-pre-alpha state), here on github:
https://github.com/YARL-project/YARL
This one will - probably in a few months - have a full IMPALA implementation including distributed computation and multi-GPU support.
Best,
Sven

**Comment by rnunziata** [comment]
Thanks....all I really want is to run the explorer in CPU and the learner as GPU.  Not sure how to do that the training monitor. Thanks for you reply.
